#pragma once

#include "MTGL_core.h"

#include <stdint.h>

// compression methods
#define FONT_COMPRESSION_NONE      0 // (uncompressed image_data)
#define FONT_COMPRESSION_LZ77      1 // LZ77~ compression

// used compression method
#ifndef FONT_COMPRESSION_METHOD
#define FONT_COMPRESSION_METHOD    FONT_COMPRESSION_LZ77
#endif

// font character decompression buffer size
#ifndef FONT_DECOMPRESSION_BUFFER_SIZE
#define FONT_DECOMPRESSION_BUFFER_SIZE   (40 * 40)
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    TEXT_ALIGNMENT_VERTICAL_TOP     = 0,
    TEXT_ALIGNMENT_VERTICAL_MIDDLE  = 1,
    TEXT_ALIGNMENT_VERTICAL_BOTTOM  = 2,
    TEXT_ALIGNMENT_VERTICAL_JUSTIFY = 3,
} TextAlignmentVertical;

typedef enum {
    TEXT_ALIGNMENT_HORIZONTAL_LEFT    = 0,
    TEXT_ALIGNMENT_HORIZONTAL_CENTER  = 1,
    TEXT_ALIGNMENT_HORIZONTAL_RIGHT   = 2,
    TEXT_ALIGNMENT_HORIZONTAL_JUSTIFY = 3,
} TextAlignmentHorizontal;

typedef enum {
    TEXT_ALIGNMENT_TOP_LEFT        = (TEXT_ALIGNMENT_VERTICAL_TOP << 2)     | TEXT_ALIGNMENT_HORIZONTAL_LEFT, // default
    TEXT_ALIGNMENT_TOP_CENTER      = (TEXT_ALIGNMENT_VERTICAL_TOP << 2)     | TEXT_ALIGNMENT_HORIZONTAL_CENTER,
    TEXT_ALIGNMENT_TOP_RIGHT       = (TEXT_ALIGNMENT_VERTICAL_TOP << 2)     | TEXT_ALIGNMENT_HORIZONTAL_RIGHT,
    TEXT_ALIGNMENT_TOP_JUSTIFY     = (TEXT_ALIGNMENT_VERTICAL_TOP << 2)     | TEXT_ALIGNMENT_HORIZONTAL_JUSTIFY,
    TEXT_ALIGNMENT_MIDDLE_LEFT     = (TEXT_ALIGNMENT_VERTICAL_MIDDLE << 2)  | TEXT_ALIGNMENT_HORIZONTAL_LEFT,
    TEXT_ALIGNMENT_MIDDLE_CENTER   = (TEXT_ALIGNMENT_VERTICAL_MIDDLE << 2)  | TEXT_ALIGNMENT_HORIZONTAL_CENTER,
    TEXT_ALIGNMENT_MIDDLE_RIGHT    = (TEXT_ALIGNMENT_VERTICAL_MIDDLE << 2)  | TEXT_ALIGNMENT_HORIZONTAL_RIGHT,
    TEXT_ALIGNMENT_MIDDLE_JUSTIFY  = (TEXT_ALIGNMENT_VERTICAL_MIDDLE << 2)  | TEXT_ALIGNMENT_HORIZONTAL_JUSTIFY,
    TEXT_ALIGNMENT_BOTTOM_LEFT     = (TEXT_ALIGNMENT_VERTICAL_BOTTOM << 2)  | TEXT_ALIGNMENT_HORIZONTAL_LEFT,
    TEXT_ALIGNMENT_BOTTOM_CENTER   = (TEXT_ALIGNMENT_VERTICAL_BOTTOM << 2)  | TEXT_ALIGNMENT_HORIZONTAL_CENTER,
    TEXT_ALIGNMENT_BOTTOM_RIGHT    = (TEXT_ALIGNMENT_VERTICAL_BOTTOM << 2)  | TEXT_ALIGNMENT_HORIZONTAL_RIGHT,
    TEXT_ALIGNMENT_BOTTOM_JUSTIFY  = (TEXT_ALIGNMENT_VERTICAL_BOTTOM << 2)  | TEXT_ALIGNMENT_HORIZONTAL_JUSTIFY,
    TEXT_ALIGNMENT_JUSTIFY_LEFT    = (TEXT_ALIGNMENT_VERTICAL_JUSTIFY << 2) | TEXT_ALIGNMENT_HORIZONTAL_LEFT,
    TEXT_ALIGNMENT_JUSTIFY_CENTER  = (TEXT_ALIGNMENT_VERTICAL_JUSTIFY << 2) | TEXT_ALIGNMENT_HORIZONTAL_CENTER,
    TEXT_ALIGNMENT_JUSTIFY_RIGHT   = (TEXT_ALIGNMENT_VERTICAL_JUSTIFY << 2) | TEXT_ALIGNMENT_HORIZONTAL_RIGHT,
    TEXT_ALIGNMENT_JUSTIFY_JUSTIFY = (TEXT_ALIGNMENT_VERTICAL_JUSTIFY << 2) | TEXT_ALIGNMENT_HORIZONTAL_JUSTIFY,
} TextAlignment;

typedef struct {
	uint16_t width;
	uint16_t height;
	uint16_t bytes_per_line;
	uint16_t height_offset;
	uint32_t unicode;
	uint8_t *data;
	uint32_t data_length;
} Character;

typedef struct {
	uint16_t font_size;
	uint8_t bits_per_pixel;
	uint16_t character_count;
	Character **character_table;
} Font;

typedef struct {
    const Font *font;
    float line_spacing;
    uint8_t brightness;
    MTGLSize area;
    TextAlignment alignment;
} StringFormat;

void MTGL_drawString(const char *str, int pos_x, int pos_y, StringFormat *format);

MTGLSize Font_getStringSize(const char *str, const Font *font, float line_spacing);

#ifdef __cplusplus
}
#endif
